

Customer.create!(first_name: "Max", last_name: "Charles", username: "ConeBone69", password: "password")
Customer.create!(first_name: "Katy", last_name:"Perry", username: "KP33", password: "password")
Customer.create!(first_name: "Megan", last_name: "Fox", username: "FoxyLady123", password: "password")
Customer.create!(first_name: "Brian", last_name: "May", username: "KingOfQueen", password:"password")
Customer.create!(first_name: "Jeff", last_name: "Buckley", username:"LESpizzaguy", password: "password")
Customer.create!(first_name: "Bruce", last_name: "Springsteen", username: "BossManInUSA", password: "password")
Customer.create!(first_name: "Emma", last_name: "Roberts", username: "NotJulia924", password: "password")
Customer.create!(first_name: "April", last_name: "O'Neil", username: "YellowSuitNews", password: "password")
Customer.create!(first_name: "Keith", last_name: "Richards", username: "ZombieManVinyl", password: "password")
Customer.create!(first_name: "Alex", last_name: "D'Addario", username: "IASIPsuperPhan", password: "password")
Customer.create!(first_name: "Seth", last_name: "Rogen", username: "EfficientPineapple", password: "password")
Customer.create!(first_name: "Darth", last_name: "Maul", username: "SithRuleGalaxy3", password: "password")
Customer.create!(first_name: "Nic", last_name: "Cage", username: "PressleyGone34", password: "password")
Customer.create!(first_name: "Sara", last_name: "Malakul-Lane", username: "23Tequillas", password: "password")
Customer.create!(first_name: "Paul", last_name: "Rudd", username: "Antman2020", password: "password")
Customer.create!(first_name: "Diana", last_name: "Agron", username: "MumfordFan1105", password: "password")
Customer.create!(first_name: "Kat", last_name: "Dennings", username: "BrokeGirl1105", password: "password")
Customer.create!(first_name: "Margot", last_name: "Robbie", username: "OutbackBabe1105", password: "password")
Customer.create!(first_name: "Tom", last_name: "Hanks", username: "Castaway1105", password: "password")
Customer.create!(first_name: "Keanu", last_name: "Reeves", username: "IKnowKungFuToo", password: "password")

Instrument.create!(instrument_type: "electric guitar", name: "90's Vintage Rock", make: "Fender", model: "Telecaster", color: "Spotted Atrocious Purple", year_made: 1992)
Instrument.create!(instrument_type: "electric guitar", name: "50's American Vintage", make: "Fender", model: "Stratocaster", color: "Daphne Blue", year_made: 1956)
Instrument.create!(instrument_type: "electric guitar", name: "Classic", make: "Gibson", model: "Les Paul", color: "Sunburst", year_made: 1992)
Instrument.create!(instrument_type: "electric guitar", name: "Brian May Signature", make: "Brian May Guitars", model: "Brian May Signature", color: "Antique Cherry", color: 2016)
Instrument.create!(instrument_type: "electric guitar", name: "FSR Two Tone", make: "Gretsch", model: "Electromatic Double Jet", color: "Surf Green & White", color: 2020)
Instrument.create!(instrument_type: "acoustic guitar", name: "Standard", make: "Gibson", model: "Hummingbird", color: "Cherry Sunburst", color: 1972)
Instrument.create!(instrument_type: "acoustic guitar", name: "224ce-K DLX", make: "Taylor", model: "Grand Auditorium Acoustic-Electric", color: "Shaded Edge Burst", color: 2018)
Instrument.create!(instrument_type: "acoustic guitar", name: "D-45 Standard", make: "Martin", model: "Dreadnought", color: "Aged Toner", color: 2015)
Instrument.create!(instrument_type: "acoustic guitar", name: "17 Series-000-17E", make: "Martin", model: "Auditorium Acoustic-Electric", color: "Whiskey Sunset", color: 2009)
Instrument.create!(instrument_type: "electric bass", name: "American", make: "Fender", model: "Precision Bass", color: "Vintage Sunburst", color: 1968)
Instrument.create!(instrument_type: "electric bass", name: "American Ultra", make: "Fender", model: "Jazz Bass", color: "Cobra Blue", color: 1982)
Instrument.create!(instrument_type: "electric bass", name: "JMJ Custom", make: "Fender", model: "Mustang Bass", color: "Daphne Blue", color: 2018)
Instrument.create!(instrument_type: "electric bass", name: "Music Man", make: "Ernie Ball", model: "Stingray", color: "Black", color: 1972)

MusicStore.create!(name: "GIT YOUR GEETS!", address: "1538 E Passyunk Ave, Philadelphia, PA 19147")
MusicStore.create!(name: "Triple R Guitar", address: "300 Market St, Lemoyne, PA 17043")
MusicStore.create!(name: "Emerald City Guitars", address: "83 S Washington St, Seattle, WA 98104")