
# Liam = Customer.create!(name: "Liam "Tinney", Mav828", password: "password", password_digest: "password")

Customer.create!(name: "Conan O'Brien", password: "password", password_digest: "password")
Customer.create!(name: "Katy Perry", password: "password", password_digest: "password")
Customer.create!(name: "Megan Fox", password: "password", password_digest: "password")
Customer.create!(name: "Brian May", password:"password", password_digest: "password")
Customer.create!(name: "Jeff Buckley", password: "password", password_digest: "password")
Customer.create!(name: "Bruce Springsteen", password: "password", password_digest: "password")
Customer.create!(name: "Emma Roberts", password: "password", password_digest: "password")
Customer.create!(name: "April O'Neil",  password: "password", password_digest: "password")
Customer.create!(name: "Keith Richards", password: "password", password_digest: "password")
Customer.create!(name: "Alex D'Addario", password: "password", password_digest: "password")
Customer.create!(name: "Seth Rogen", password: "password", password_digest: "password")
Customer.create!(name: "Darth Maul", password: "password", password_digest: "password")
Customer.create!(name: "Nic Cage", password: "password", password_digest: "password")
Customer.create!(name: "Sara Malakul-Lane", password: "password", password_digest: "password")
Customer.create!(name: "Paul Rudd", password: "password", password_digest: "password")
Customer.create!(name: "Diana Agron", password: "password", password_digest: "password")
Customer.create!(name: "Kat Dennings", password: "password", password_digest: "password")
Customer.create!(name: "Margot Robbie", password: "password", password_digest: "password")
Customer.create!(name: "Tom Hanks", password: "password", password_digest: "password")
Customer.create!(name: "Keanu Reeves", password: "password", password_digest: "password")

Instrument.create!(instrument_type: "electric guitar", name: "90's Vintage Rock", make: "Fender", model: "Telecaster", color: "Spotted Atrocious Purple", year_made: 1992)
Instrument.create!(instrument_type: "electric guitar", name: "50's American Vintage", make: "Fender", model: "Stratocaster", color: "Daphne Blue", year_made: 1956)
Instrument.create!(instrument_type: "electric guitar", name: "Classic", make: "Gibson", model: "Les Paul", color: "Sunburst", year_made: 1992)
Instrument.create!(instrument_type: "electric guitar", name: "Signature", make: "Brian May Guitars", model: "Brian May Signature", color: "Antique Cherry", year_made: 2016)
Instrument.create!(instrument_type: "electric guitar", name: "FSR Two Tone", make: "Gretsch", model: "Electromatic Double Jet", color: "Surf Green & White", year_made: 2020)
Instrument.create!(instrument_type: "acoustic guitar", name: "Standard", make: "Gibson", model: "Hummingbird", color: "Cherry Sunburst", year_made: 1972)
Instrument.create!(instrument_type: "acoustic guitar", name: "224ce-K DLX", make: "Taylor", model: "Grand Auditorium Acoustic-Elec", color: "Shaded Edge Burst", year_made: 2018)
Instrument.create!(instrument_type: "acoustic guitar", name: "D-45 Standard", make: "Martin", model: "Dreadnought", color: "Aged Toner", year_made: 2015)
Instrument.create!(instrument_type: "acoustic guitar", name: "17 Series-000-17E", make: "Martin", model: "Auditorium Acoustic-Electric", color: "Whiskey Sunset", year_made: 2009)
Instrument.create!(instrument_type: "electric bass", name: "American", make: "Fender", model: "Precision Bass", color: "Vintage Sunburst", year_made: 1968)
Instrument.create!(instrument_type: "electric bass", name: "American Ultra", make: "Fender", model: "Jazz Bass", color: "Cobra Blue", year_made: 1982)
Instrument.create!(instrument_type: "electric bass", name: "JMJ Custom", make: "Fender", model: "Mustang Bass", color: "Daphne Blue", year_made: 2018)
Instrument.create!(instrument_type: "electric bass", name: "Music Man", make: "Ernie Ball", model: "Stingray", color: "Black", year_made: 1972)

MusicStore.create!(name: "GIT YOUR GEETS!", address: "1538 E Passyunk Ave, Philadelphia, PA 19147")
MusicStore.create!(name: "Triple R Guitar", address: "300 Market St, Lemoyne, PA 17043")
MusicStore.create!(name: "Emerald City Guitars", address: "83 S Washington St, Seattle, WA 98104")